spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fz-user-center
    username: root
    password: root
  #profiles:
    #active: prod

  session:
    timeout: 86400 #session失效时间 一天