spring:
  application:
    name: user-center
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fz-user-center
    username: root
    password: root
  session:
    timeout: 86400 #session失效时间 一天
server:
  port: 8080
  servlet:
    context-path: '/api'

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      local-delete-field: isDelete #全局逻辑删除的实体字段名
      logic-delete-value: 1 #逻辑已删除值（默认为1）
      logic-not-delete-value: 0 #逻辑未删除值（默认为0）